name: Deploy on gh-pages

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    name: Build and Release
    runs-on: ubuntu-latest
    # Disable pre release builds
    if: ${{ ! contains(github.ref, '-') }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install Packages
      run: npm install
    - name: Build App
      run: npm run build
      env:
        # React will fail CI if there is any warning
        CI: false
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        publish_branch: gh-pages
        user_name: github-actions[bot]
        user_email: github-actions[bot]@users.noreply.github.com
