name: Deploy on gh-pages

on:
  push:
    tags: 
      - 'v*'

env:
  NODE_VERSION: '12.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - uses: actions/checkout@v2
      with:
        submodules: true
        path: head
    - name: Install Packages
      run: |
        cd head
        npm install
    - name: Build Latest (Beta) App
      run: |
        cd head
        npm run build
      env:
        # React will fail CI if there is any warning
        CI: false
        PUBLIC_PATH: '/PKUHoleCommunity/beta/'
    - name: Prepare Latest Pages
      if: ${{ contains(github.ref, '-') }}
      uses: actions/checkout@v2
      with:
        submodules: true
        path: dist
        ref: 'gh-pages'
    - name: Validate Previous Pages (Backward & Error Compacity)
      id: validate
      run: |
        if [ -d 'dist/stable' ]
        then
          echo '::set-output name=valid::true'
        else
          rm -rf dist/*
          echo '::set-output name=valid::false'
        fi
    - name: Copy Beta Version
      run: |
        rm -rf dist/beta/
        cp -r head/build/ dist/beta/
    - name: Also Copy as Stable
      if: ${{ ! contains(github.ref, '-') }}
      run: |
        rm -rf dist/stable/
        cp -r head/build/ dist/stable/
    - name: Rebuild Stable Version
      if: ${{ ! steps.validate.outputs.valid }}
      run: |
        cp head/redirect.html dist/index.html
        cd head
        git checkout "v$(semver $(git tag) | tail -n 1)"
        npm install
        npm run build
        cp -r build ../dist/stable
      env:
        CI: false
        PUBLIC_PATH: '/PKUHoleCommunity/stable/'
    - uses: actions/upload-artifact@v2
      with:
        name: build-result
        path: |
          dist
          !dist/.git
