name: Deploy on gh-pages

on:
  push:
    tags:
      - "v*"

env:
  NODE_VERSION: "12.x"

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/checkout@v2
        with:
          submodules: true
          path: head
      
      - name: debug
        run: |
          cd head
          git pull origin master --unshallow

      - name: Install Packages
        run: |
          cd head
          npm install
      - name: Build Latest (Beta) App
        run: |
          cd head
          npm run build
        env:
          # React will fail CI if there is any warning
          CI: false
          PUBLIC_URL: "/beta/"

      - name: Prepare Latest Gitee Pages
        run: |
          git clone --depth=1 https://gitee.com/PKUHoleCE/PKUHoleCE.git dist

      - name: (Pre) Validate Previous Pages (Backward & Error Compacity)
        if: ${{ contains(github.ref, '-') }}
        id: validate
        run: |
          if [ -d 'dist/stable' ]
          then
            echo '::set-output name=valid::true'
          else
            rm -rf dist/*
            echo '::set-output name=valid::'
          fi
      - name: Copy Beta Version
        run: |
          rm -rf dist/beta/
          cp -r head/build/ dist/beta/
      - name: (Stable) Also Copy as Stable
        if: ${{ ! contains(github.ref, '-') }}
        run: cp -r head/build/ dist/stable/

      - name: (Pre) Rebuild Stable Version
        if: ${{ ! steps.validate.outputs.valid && contains(github.ref, '-') }}
        run: |
          # cp head/redirect.html dist/index.html
          cd head
          # fetch all history and tags
          git checkout master
          git pull --unshallow
          # checkout latest stable version
          git checkout "v$(npx semver -r '>0.0.0' $(git tag) | tail -n 1)"
          npm install
          npm run build
          cp -r build ../dist/stable
        env:
          CI: false
          PUBLIC_URL: "/stable/"

      - name: Push to Gitee
        run: |
          cd dist
          git commit -m "Deploy $REF"
          echo -e "AllanChain\n$PASSWORD" | git push
        env:
          REF: ${{ github.ref }}
          PASSWORD: ${{ secrets.GITEE_PASSWORD }}
      
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@master
        with:
          gitee-username: AllanChain
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: PKUHoleCE/PKUHoleCE
