name: Deploy on gitee pages

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/checkout@v2
        with:
          submodules: true
          path: head

      - name: Setup Committer
        run: |
          git config --global user.email "pkuholece-bot@outlook.com"
          git config --global user.name "pkuholece-bot"
          echo "machine gitee.com login pkuholece-bot password $PASSWORD" >> ~/.netrc
        env:
          PASSWORD: ${{ secrets.GITEE_PASSWORD }}

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Install Packages
        working-directory: head
        run: pnpm install

      - name: Build Latest (Beta) App
        working-directory: head
        run: pnpm run build --base=/beta/

      - name: Prepare Latest Gitee Pages
        run: |
          git clone --depth=1 https://gitee.com/PKUHoleCE/PKUHoleCE.git dist

      - name: (Pre) Validate Previous Pages (Backward & Error Compatibility)
        if: ${{ contains(github.ref, '-') }}
        id: validate
        run: |
          if [ -d 'dist/stable' ]
          then
            echo '::set-output name=valid::true'
          else
            rm -rf dist/*
            echo '::set-output name=valid::'
          fi

      - name: Copy Beta Version
        run: |
          rm -rf dist/beta/
          cp -r head/build/ dist/beta/

      - name: (Stable) Build Again with /stable/
        if: ${{ ! contains(github.ref, '-') }}
        run: |
          cd head
          pnpm run build --base=/stable/
          cd ..
          rm -rf dist/stable/
          cp -r head/build/ dist/stable/

      - name: (Pre) Rebuild Stable Version
        if: ${{ ! steps.validate.outputs.valid && contains(github.ref, '-') }}
        run: |
          cd head
          # fetch all history and tags
          git pull origin master --unshallow --tags
          # checkout latest stable version
          git checkout "v$(npx semver -r '>0.0.0' $(git tag) | tail -n 1)"
          pnpm install
          pnpm run build --base=/stable/
          cp -r build ../dist/stable

      - name: Push to Gitee
        run: |
          cp head/README.md dist/
          cd dist
          git add .
          git commit -m "Deploy $REF"
          git push
        env:
          REF: ${{ github.ref }}

