on:
  push:
    tags:
      - 'v*'
      # do not release on ci testing
      - '!v*ci*'
      - '!v*debug*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Changelog
        run: |
          yarn global add conventional-changelog-cli
          export PATH="$HOME/.yarn/bin:$PATH"
          conventional-changelog -r 2 -p angular > .changelog
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          body_path: .changelog
          prerelease: ${{ contains(github.ref, '-') }}
