on:
  push:
    branches:
      - master
      - ci*

env:
  NODE_VERSION: '12.x'

jobs:
  build-and-deploy:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Prepare Content to Hash (ignore app version)
      run: tail -n +4 package-lock.json > .content.to.hash
    - uses: actions/cache@v2
      id: cache
      with:
        path: ~/.npm
        key: node-${{ hashFiles('.content.to.hash') }}
        restore-keys: |
          node-
    - name: Install Packages
      # No need to install if hit, we are not building
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install
